DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS follow CASCADE;
DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  confirmed BOOLEAN DEFAULT FALSE,
  profile_picture VARCHAR(255) DEFAULT 'defaultProfile.jpg',
  background_picture VARCHAR(255) DEFAULT 'defaultBackground.png'
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  image VARCHAR(255),
  date_created TIMESTAMP,
  owner_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  owner_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  date TIMESTAMP
);

CREATE TABLE likes (
  id SERIAL PRIMARY KEY,
  owner_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
  date TIMESTAMP
);

CREATE TABLE follow (
  follower INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  following INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (follower, following)
);
